# Site settings
title: Husabergbakken Velforening 
author:
  name: Husabergbakken velforening styre
  email: husabergbakkenvelforening@gmail.com 
description: "Husabergbakken Velforening"

# Build settings
remote_theme: jekyll/minima