# Site settings
title: Husabergbakken Velforening config 
author:
  name: Husabergbakken velforening styre
  email: husabergbakkenvelforening@gmail.com 
description: "Husabergbakken Velforening from config"

# Build settings
remote_theme: jekyll/minima